name: Auto-merge Dependabot
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'pre-commit-ci[bot]'
    steps:
    - name: Enable Pull Request Automerge
      run: gh pr merge --merge --squash --auto
      env:
        GH_TOKEN: ${{ secrets.PAT }}
